version: "3"
services:
  web:
    image: latra/hello-docker:first
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
      - "4000:80"
    networks:
      - webnet
networks:
  webnet: